version: "3.1"

services:
  site:
    build: ./config/site
    container_name: online-judge
    restart: always
    environment:
      - WAIT_HOSTS=db:3306
    ports:
      - 80:80
      - 443:443
      - 9999:9999
      - 9998:9998
      - 15100:15100
      - 15101:15101
      - 15102:15102
    networks:
      - dmoj-net
    volumes:
      - dmoj-site:/site
      - dmoj-problems:/problems
    depends_on:
      - db

  judge:
    build: ./config/judge
    container_name: judge-server
    privileged: true
    restart: always
    depends_on:
      - site
    networks:
      - dmoj-net
    volumes:
      - dmoj-problems:/problems
    env_file:
      - config/judge/judge.env

  db:
    image: mariadb:10.3.10
    environment:
      - MYSQL_ROOT_PASSWORD=dmoj
      - MYSQL_DATABASE=dmoj
    networks:
      - dmoj-net
    volumes:
      - dmoj-db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
    dmoj-problems:
        driver: local
    dmoj-db:
        driver: local
    dmoj-site:
        driver: local
networks:
    dmoj-net:
        driver: bridge