#!/bin/bash

export DMOJ_IN_DOCKER=1
export PYTHONUNBUFFERED=1
export LANG=C.UTF-8
export PYTHONIOENCODING=utf8

cd /judge || exit
pip3 install -q -e .

shift
. ~judge/.profile

dmoj-autoconf > /judge.yml
echo 'problem_storage_root:
- /problems
' >> /judge.yml

runuser -u judge "dmoj -c ./judge.yml $JUDGE_SITE $JUDGE_NAME $JUDGE_KEY"
