#!/bin/bash

export DMOJ_IN_DOCKER=1
export PYTHONUNBUFFERED=1
export LANG=C.UTF-8
export PYTHONIOENCODING=utf8

cd /judge || exit
pip3 install -q -e .

case "$1" in
run) command=(dmoj) ;;
cli) command=(dmoj-cli) ;;
test) command=(python3 -- -m dmoj.testsuite testsuite) ;;
*)
#  echo "Invalid command, must be one of [run, cli, test]" 1>&2
  # shellcheck disable=SC2206
  # shellcheck disable=SC2034
  command=(dmoj -c /judge.yml $JUDGE_SITE $JUDGE_NAME $JUDGE_KEY)
  ;;
esac

shift
. ~judge/.profile

runuser -u judge "dmoj-autoconf > /judge.yml"
echo 'problem_storage_root:
- /problems
' >> /judge.yml

runuser -u judge "${command[@]}" -- "$@"
